version: '2'
services:
    yyoa-app:
        image: yyoa
        external_links:
            - yyoa-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/yyOa
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    yyoa-postgresql:
        extends:
            file: postgresql.yml
            service: yyoa-postgresql
