version: '2'
services:
    yiyingoa-mariadb:
        container_name: yiyingoa-mariadb
        image: mariadb:10.1.17
        # volumes:
        #     - ~/volumes/jhipster/YiyingOA/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=yiyingoa
        ports:
            - 3306:3306
