version: '2'
services:
    yiyingoa-postgresql:
        container_name: yiyingoa-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/yiyingOa/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=yiyingOa
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
